/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pcd;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author Yorozuya
 */
public class MainFrame extends javax.swing.JFrame {
    public BufferedImage img;
    LoadImage li;
    Sampling ds;
    Quantize qi;
    Zoom zin;
    Rotate rot;
    Flip flip;
    Crop crop;
    Histogram hist;
    Filter fm;
    Segmentation sg;
    Morphology mp;
    int defWIdth=503;
    int defHeight=457;
    
    BufferedImage imgOut;
    String dirL;
    String dirS;
    /**
     * Creates new form MainFrame
     */
    public MainFrame(BufferedImage img, LoadImage li, Sampling ds, Quantize qi, Zoom zin, Rotate rot45, Flip flip, Crop crop, Histogram hist, Filter FM, Segmentation SG, Morphology mp) {
        initComponents();
        this.setTitle("Image Processing V.1.0 by @yorozuya");
        this.img=img;
        this.li=li;
        this.ds=ds;
        this.qi=qi;
        this.zin=zin;
        this.rot=rot45;
        this.flip=flip;
        this.crop=crop;
        this.hist=hist;
        this.fm=FM;
        this.sg=SG;
        this.mp=mp;
        
        imgOut=img;
        
        this.setSize(defWIdth, defHeight);
        Pn_Flip.setVisible(false);
        Pn_Zoom.setVisible(false);
        Pn_Filter.setVisible(false);
        Pn_Hist.setVisible(false);
        Pn_Segment.setVisible(false);
        Pn_Morph.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pn_Main = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btLoad = new javax.swing.JButton();
        btSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfDir = new javax.swing.JTextField();
        btCutPaste = new javax.swing.JButton();
        btResult = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btFlip = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btZoom = new javax.swing.JButton();
        btSampling = new javax.swing.JButton();
        tfDirS = new javax.swing.JTextField();
        btFil = new javax.swing.JButton();
        btSeg = new javax.swing.JButton();
        btHis = new javax.swing.JButton();
        btMorp = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btQuant = new javax.swing.JButton();
        bgMain = new javax.swing.JLabel();
        Pn_Flip = new javax.swing.JPanel();
        btHFlip = new javax.swing.JButton();
        btVFlip = new javax.swing.JButton();
        btBack = new javax.swing.JButton();
        bg = new javax.swing.JLabel();
        Pn_Zoom = new javax.swing.JPanel();
        btZIn = new javax.swing.JButton();
        btZOut = new javax.swing.JButton();
        btBack1 = new javax.swing.JButton();
        bg1 = new javax.swing.JLabel();
        Pn_Filter = new javax.swing.JPanel();
        btSharp = new javax.swing.JButton();
        btMean = new javax.swing.JButton();
        btMed = new javax.swing.JButton();
        btMod = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btEdgeLapN = new javax.swing.JButton();
        btPreNW = new javax.swing.JButton();
        btEdgeLap = new javax.swing.JButton();
        btEdgeLapP = new javax.swing.JButton();
        btEdgeFr = new javax.swing.JButton();
        btSob = new javax.swing.JButton();
        btSobX = new javax.swing.JButton();
        btSobY = new javax.swing.JButton();
        btPre = new javax.swing.JButton();
        btPreN = new javax.swing.JButton();
        btPreNE = new javax.swing.JButton();
        btPreE = new javax.swing.JButton();
        btPreSE = new javax.swing.JButton();
        btPreS = new javax.swing.JButton();
        btPreSW = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        btPreW = new javax.swing.JButton();
        btBack2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Pn_Hist = new javax.swing.JPanel();
        btGray = new javax.swing.JButton();
        btHistEQ = new javax.swing.JButton();
        btBack3 = new javax.swing.JButton();
        bg2 = new javax.swing.JLabel();
        Pn_Segment = new javax.swing.JPanel();
        btThresh = new javax.swing.JButton();
        btBack4 = new javax.swing.JButton();
        btBin = new javax.swing.JButton();
        bg3 = new javax.swing.JLabel();
        Pn_Morph = new javax.swing.JPanel();
        btEro = new javax.swing.JButton();
        btBack5 = new javax.swing.JButton();
        btDil = new javax.swing.JButton();
        bg4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        Pn_Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tele-Marines", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Image Processing V.1.0");
        Pn_Main.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        btLoad.setText("Load Image");
        btLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoadActionPerformed(evt);
            }
        });
        Pn_Main.add(btLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 363, -1, -1));

        btSave.setText("Save Image");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        Pn_Main.add(btSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 363, -1, -1));

        jLabel2.setText("Load Image Directory :");
        Pn_Main.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 140, -1));

        tfDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDirActionPerformed(evt);
            }
        });
        Pn_Main.add(tfDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 352, -1));

        btCutPaste.setBackground(new java.awt.Color(102, 204, 255));
        btCutPaste.setText("Cut & Paste");
        btCutPaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCutPasteActionPerformed(evt);
            }
        });
        Pn_Main.add(btCutPaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 61, -1, -1));

        btResult.setText("Show Result");
        btResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResultActionPerformed(evt);
            }
        });
        Pn_Main.add(btResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 363, -1, -1));

        jLabel3.setFont(new java.awt.Font("MV Boli", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Basic Image Operation");
        Pn_Main.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        btFlip.setBackground(new java.awt.Color(0, 255, 255));
        btFlip.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btFlip.setText("Flip");
        btFlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFlipActionPerformed(evt);
            }
        });
        Pn_Main.add(btFlip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 89, -1));

        jButton2.setBackground(new java.awt.Color(102, 204, 255));
        jButton2.setText("Rotate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Pn_Main.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 61, -1, -1));

        btZoom.setBackground(new java.awt.Color(0, 255, 255));
        btZoom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btZoom.setText("Zoom");
        btZoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btZoomActionPerformed(evt);
            }
        });
        Pn_Main.add(btZoom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        btSampling.setBackground(new java.awt.Color(102, 204, 255));
        btSampling.setText("Sampling");
        btSampling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSamplingActionPerformed(evt);
            }
        });
        Pn_Main.add(btSampling, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        tfDirS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDirSActionPerformed(evt);
            }
        });
        Pn_Main.add(tfDirS, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 350, -1));

        btFil.setBackground(new java.awt.Color(102, 255, 102));
        btFil.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btFil.setText("Filter & Edge");
        btFil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFilActionPerformed(evt);
            }
        });
        Pn_Main.add(btFil, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 110, -1));

        btSeg.setBackground(new java.awt.Color(102, 255, 102));
        btSeg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSeg.setText("Segmentation");
        btSeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSegActionPerformed(evt);
            }
        });
        Pn_Main.add(btSeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        btHis.setBackground(new java.awt.Color(102, 255, 102));
        btHis.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btHis.setText("Histogram EQ");
        btHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHisActionPerformed(evt);
            }
        });
        Pn_Main.add(btHis, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        btMorp.setBackground(new java.awt.Color(102, 255, 102));
        btMorp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btMorp.setText("Morphology");
        btMorp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMorpActionPerformed(evt);
            }
        });
        Pn_Main.add(btMorp, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 110, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 51));
        jLabel5.setText("Advanced Image Operation");
        Pn_Main.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 160, -1));

        jLabel4.setBackground(new java.awt.Color(255, 51, 51));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcd/wingcustom2.jpg"))); // NOI18N
        jLabel4.setText("Advanced Image Operation");
        Pn_Main.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, 20));

        jLabel6.setText("Save Image Directory :");
        Pn_Main.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 130, -1));

        jLabel7.setBackground(new java.awt.Color(255, 51, 51));
        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcd/wingcustom2.jpg"))); // NOI18N
        jLabel7.setText("Advanced Image Operation");
        Pn_Main.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 180, 20));

        btQuant.setBackground(new java.awt.Color(102, 204, 255));
        btQuant.setText("Quantize");
        btQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuantActionPerformed(evt);
            }
        });
        Pn_Main.add(btQuant, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        bgMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcd/xxxg_00w0_by_chaamal-d45yh3e.jpg"))); // NOI18N
        Pn_Main.add(bgMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 400));

        getContentPane().add(Pn_Main, "card2");

        Pn_Flip.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btHFlip.setText("Horizontal Flip");
        btHFlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHFlipActionPerformed(evt);
            }
        });
        Pn_Flip.add(btHFlip, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 11, 130, -1));

        btVFlip.setText("Vertical Flip");
        btVFlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVFlipActionPerformed(evt);
            }
        });
        Pn_Flip.add(btVFlip, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 45, 130, -1));

        btBack.setText("Back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });
        Pn_Flip.add(btBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 139, 130, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcd/10750330_751880558233873_3906636366357599819_o.jpg"))); // NOI18N
        Pn_Flip.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 190, 190));

        getContentPane().add(Pn_Flip, "card14");

        Pn_Zoom.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btZIn.setText("Zoom In (2x)");
        btZIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btZInActionPerformed(evt);
            }
        });
        Pn_Zoom.add(btZIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 11, 130, -1));

        btZOut.setText("Zoom Out (0.5x)");
        btZOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btZOutActionPerformed(evt);
            }
        });
        Pn_Zoom.add(btZOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 45, 130, -1));

        btBack1.setText("Back");
        btBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBack1ActionPerformed(evt);
            }
        });
        Pn_Zoom.add(btBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 139, 130, -1));

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcd/10750330_751880558233873_3906636366357599819_o.jpg"))); // NOI18N
        Pn_Zoom.add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 190, 190));

        getContentPane().add(Pn_Zoom, "card14");

        Pn_Filter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btSharp.setBackground(new java.awt.Color(255, 153, 153));
        btSharp.setText("High-pass");
        btSharp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSharpActionPerformed(evt);
            }
        });
        Pn_Filter.add(btSharp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 110, -1));

        btMean.setBackground(new java.awt.Color(204, 255, 204));
        btMean.setText("Mean Filter");
        btMean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMeanActionPerformed(evt);
            }
        });
        Pn_Filter.add(btMean, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, -1));

        btMed.setBackground(new java.awt.Color(204, 255, 204));
        btMed.setText("Median Filter");
        btMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMedActionPerformed(evt);
            }
        });
        Pn_Filter.add(btMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 110, -1));

        btMod.setBackground(new java.awt.Color(204, 255, 204));
        btMod.setText("Modus Filter");
        btMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModActionPerformed(evt);
            }
        });
        Pn_Filter.add(btMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 100, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setText("Image Sharpening");
        Pn_Filter.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 255, 204));
        jLabel9.setText("Image Blurring");
        Pn_Filter.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("Edge Detection");
        Pn_Filter.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 100, -1));

        btEdgeLapN.setBackground(new java.awt.Color(255, 255, 102));
        btEdgeLapN.setText("Laplace Negative");
        btEdgeLapN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEdgeLapNActionPerformed(evt);
            }
        });
        Pn_Filter.add(btEdgeLapN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        btPreNW.setBackground(new java.awt.Color(255, 255, 102));
        btPreNW.setText("Prewitt-Northwest");
        btPreNW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPreNWActionPerformed(evt);
            }
        });
        Pn_Filter.add(btPreNW, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 130, -1));

        btEdgeLap.setBackground(new java.awt.Color(255, 255, 102));
        btEdgeLap.setText("Laplace");
        btEdgeLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEdgeLapActionPerformed(evt);
            }
        });
        Pn_Filter.add(btEdgeLap, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 110, -1));

        btEdgeLapP.setBackground(new java.awt.Color(255, 255, 102));
        btEdgeLapP.setText("Laplace Positive");
        btEdgeLapP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEdgeLapPActionPerformed(evt);
            }
        });
        Pn_Filter.add(btEdgeLapP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 110, -1));

        btEdgeFr.setBackground(new java.awt.Color(255, 255, 102));
        btEdgeFr.setText("Frei-Chan");
        btEdgeFr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEdgeFrActionPerformed(evt);
            }
        });
        Pn_Filter.add(btEdgeFr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 110, -1));

        btSob.setBackground(new java.awt.Color(255, 255, 102));
        btSob.setText("Sobel");
        btSob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSobActionPerformed(evt);
            }
        });
        Pn_Filter.add(btSob, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 110, -1));

        btSobX.setBackground(new java.awt.Color(255, 255, 102));
        btSobX.setText("Sobel-X");
        btSobX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSobXActionPerformed(evt);
            }
        });
        Pn_Filter.add(btSobX, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 110, -1));

        btSobY.setBackground(new java.awt.Color(255, 255, 102));
        btSobY.setText("Sobel-Y");
        btSobY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSobYActionPerformed(evt);
            }
        });
        Pn_Filter.add(btSobY, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 110, -1));

        btPre.setBackground(new java.awt.Color(255, 255, 102));
        btPre.setText("Prewitt");
        btPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPreActionPerformed(evt);
            }
        });
        Pn_Filter.add(btPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 110, -1));

        btPreN.setBackground(new java.awt.Color(255, 255, 102));
        btPreN.setText("Prewitt-North");
        btPreN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPreNActionPerformed(evt);
            }
        });
        Pn_Filter.add(btPreN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 130, -1));

        btPreNE.setBackground(new java.awt.Color(255, 255, 102));
        btPreNE.setText("Prewitt-Northeast");
        btPreNE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPreNEActionPerformed(evt);
            }
        });
        Pn_Filter.add(btPreNE, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 130, -1));

        btPreE.setBackground(new java.awt.Color(255, 255, 102));
        btPreE.setText("Prewitt-East");
        btPreE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPreEActionPerformed(evt);
            }
        });
        Pn_Filter.add(btPreE, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 130, -1));

        btPreSE.setBackground(new java.awt.Color(255, 255, 102));
        btPreSE.setText("Prewitt-Southeast");
        btPreSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPreSEActionPerformed(evt);
            }
        });
        Pn_Filter.add(btPreSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 130, -1));

        btPreS.setBackground(new java.awt.Color(255, 255, 102));
        btPreS.setText("Prewitt-South");
        btPreS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPreSActionPerformed(evt);
            }
        });
        Pn_Filter.add(btPreS, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 130, -1));

        btPreSW.setBackground(new java.awt.Color(255, 255, 102));
        btPreSW.setText("Prewitt-Southwest");
        btPreSW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPreSWActionPerformed(evt);
            }
        });
        Pn_Filter.add(btPreSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 130, -1));

        jButton25.setText("Prewitt-Southwest");
        Pn_Filter.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 130, -1));

        btPreW.setBackground(new java.awt.Color(255, 255, 102));
        btPreW.setText("Prewitt-West");
        btPreW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPreWActionPerformed(evt);
            }
        });
        Pn_Filter.add(btPreW, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 130, -1));

        btBack2.setText("Back");
        btBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBack2ActionPerformed(evt);
            }
        });
        Pn_Filter.add(btBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcd/wingcustom2.jpg"))); // NOI18N
        Pn_Filter.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 130, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcd/wingcustom2.jpg"))); // NOI18N
        Pn_Filter.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 130, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcd/wingcustom2.jpg"))); // NOI18N
        Pn_Filter.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 130, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcd/mirai_millennium_sf_bg_by_pinakes-d410a2x.jpg"))); // NOI18N
        Pn_Filter.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 370));

        getContentPane().add(Pn_Filter, "card5");

        Pn_Hist.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btGray.setText("Grayscale Conversion");
        btGray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGrayActionPerformed(evt);
            }
        });
        Pn_Hist.add(btGray, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        btHistEQ.setText("Equalization");
        btHistEQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHistEQActionPerformed(evt);
            }
        });
        Pn_Hist.add(btHistEQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, -1));

        btBack3.setText("Back");
        btBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBack3ActionPerformed(evt);
            }
        });
        Pn_Hist.add(btBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 139, 130, -1));

        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcd/mirai_millennium_sf_bg_by_pinakes-d410a2x.jpg"))); // NOI18N
        Pn_Hist.add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 190, 190));

        getContentPane().add(Pn_Hist, "card14");

        Pn_Segment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btThresh.setText("Thresholding");
        btThresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThreshActionPerformed(evt);
            }
        });
        Pn_Segment.add(btThresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, -1));

        btBack4.setText("Back");
        btBack4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBack4ActionPerformed(evt);
            }
        });
        Pn_Segment.add(btBack4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 139, 130, -1));

        btBin.setText("Binary Conversion");
        btBin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBinActionPerformed(evt);
            }
        });
        Pn_Segment.add(btBin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, -1));

        bg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcd/mirai_millennium_sf_bg_by_pinakes-d410a2x.jpg"))); // NOI18N
        Pn_Segment.add(bg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 190, 190));

        getContentPane().add(Pn_Segment, "card14");

        Pn_Morph.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btEro.setText("Erosion");
        btEro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEroActionPerformed(evt);
            }
        });
        Pn_Morph.add(btEro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, -1));

        btBack5.setText("Back");
        btBack5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBack5ActionPerformed(evt);
            }
        });
        Pn_Morph.add(btBack5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 139, 130, -1));

        btDil.setText("Dilation");
        btDil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDilActionPerformed(evt);
            }
        });
        Pn_Morph.add(btDil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        bg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pcd/mirai_millennium_sf_bg_by_pinakes-d410a2x.jpg"))); // NOI18N
        Pn_Morph.add(bg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 190, 190));

        getContentPane().add(Pn_Morph, "card14");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoadActionPerformed
        // TODO add your handling code here:
        dirL=tfDir.getText();
        try {
            img = ImageIO.read(new File(dirL));
        } catch (IOException ex) {
            Logger.getLogger(PCD.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        JFrame f = new JFrame("Loaded Image");
//        f.addWindowListener(new WindowAdapter(){
//                public void windowClosing(WindowEvent e) {
//                    System.exit(0);
//                }
//            });
 
        f.add(new LoadImage(dirL,dirS));
        f.pack();
        f.setVisible(true);
    }//GEN-LAST:event_btLoadActionPerformed

    private void tfDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDirActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
    try {
        // TODO add your handling code here:
        dirS=tfDirS.getText();
        LoadImage liS = new LoadImage(dirL, dirS);
        liS.saveImage(img);
    } catch (IOException ex) {
        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_btSaveActionPerformed

    private void btCutPasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCutPasteActionPerformed
        // TODO add your handling code here:
        img=crop.cropSquare(img);
    }//GEN-LAST:event_btCutPasteActionPerformed

    private void btResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResultActionPerformed
        // TODO add your handling code here:
        JFrame f = new JFrame("Processed Image");
//        f.addWindowListener(new WindowAdapter(){
//                public void windowClosing(WindowEvent e) {
//                    System.exit(0);
//                }
//            });
 
        f.add(new LoadImage(dirS,dirS));
        f.pack();
        f.setVisible(true);
    }//GEN-LAST:event_btResultActionPerformed

    private void btZoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btZoomActionPerformed
        // TODO add your handling code here:
       this.setSize(195, 210);
       Pn_Zoom.setVisible(true);
       Pn_Main.setVisible(false);
    }//GEN-LAST:event_btZoomActionPerformed

    private void btFlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFlipActionPerformed
        // TODO add your handling code here:
       this.setSize(195, 210);
       Pn_Flip.setVisible(true);
       Pn_Main.setVisible(false);
    }//GEN-LAST:event_btFlipActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        // TODO add your handling code here:
       this.setSize(defWIdth, defHeight);
       Pn_Flip.setVisible(false);
       Pn_Main.setVisible(true);
    }//GEN-LAST:event_btBackActionPerformed

    private void btHFlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHFlipActionPerformed
        // TODO add your handling code here:
        img=flip.flipH(img);
    }//GEN-LAST:event_btHFlipActionPerformed

    private void btVFlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVFlipActionPerformed
        // TODO add your handling code here:
        img=flip.flipV(img);
    }//GEN-LAST:event_btVFlipActionPerformed

    private void tfDirSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDirSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDirSActionPerformed

    private void btZInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btZInActionPerformed
        // TODO add your handling code here:
        imgOut=img;
        img=new BufferedImage(imgOut.getWidth()*2, imgOut.getHeight()*2, BufferedImage.TYPE_INT_RGB);
        img=zin.zoomIn(imgOut);
    }//GEN-LAST:event_btZInActionPerformed

    private void btZOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btZOutActionPerformed
        // TODO add your handling code here:
        imgOut=img;
        img=new BufferedImage(imgOut.getWidth()/2, imgOut.getHeight()/2, BufferedImage.TYPE_INT_RGB);
        img=zin.zoomOut(imgOut);
    }//GEN-LAST:event_btZOutActionPerformed

    private void btBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBack1ActionPerformed
        // TODO add your handling code here:
        this.setSize(defWIdth, defHeight);
        Pn_Zoom.setVisible(false);
        Pn_Main.setVisible(true);
    }//GEN-LAST:event_btBack1ActionPerformed

    private void btSamplingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSamplingActionPerformed
        // TODO add your handling code here:
        img=ds.Sampling(img);
    }//GEN-LAST:event_btSamplingActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        img=rot.rotateBeta(img);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btFilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFilActionPerformed
        // TODO add your handling code here:
        //this.setSize(defWIdth, defHeight);
        Pn_Filter.setVisible(true);
        Pn_Main.setVisible(false);
    }//GEN-LAST:event_btFilActionPerformed

    private void btBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBack2ActionPerformed
        // TODO add your handling code here:
        this.setSize(defWIdth, defHeight);
        Pn_Filter.setVisible(false);
        Pn_Main.setVisible(true);
    }//GEN-LAST:event_btBack2ActionPerformed

    private void btMeanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMeanActionPerformed
        // TODO add your handling code here:
        img=fm.meanFilter3(img);
    }//GEN-LAST:event_btMeanActionPerformed

    private void btMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMedActionPerformed
        // TODO add your handling code here:
        img=fm.medianFilter3(img);
    }//GEN-LAST:event_btMedActionPerformed

    private void btModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModActionPerformed
        // TODO add your handling code here:
        img=fm.modusFilter3(img);
    }//GEN-LAST:event_btModActionPerformed

    private void btSharpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSharpActionPerformed
        // TODO add your handling code here:
        img=fm.sharpen(img);
    }//GEN-LAST:event_btSharpActionPerformed

    private void btEdgeFrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEdgeFrActionPerformed
        // TODO add your handling code here:
        img=fm.edgeFreiChan(img);
    }//GEN-LAST:event_btEdgeFrActionPerformed

    private void btEdgeLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEdgeLapActionPerformed
        // TODO add your handling code here:
        img=fm.edgeLaplace(img);
    }//GEN-LAST:event_btEdgeLapActionPerformed

    private void btEdgeLapPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEdgeLapPActionPerformed
        // TODO add your handling code here:
        img=fm.edgeLaplaceP(img);
    }//GEN-LAST:event_btEdgeLapPActionPerformed

    private void btEdgeLapNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEdgeLapNActionPerformed
        // TODO add your handling code here:
        img=fm.edgeLaplaceN(img);
    }//GEN-LAST:event_btEdgeLapNActionPerformed

    private void btSobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSobActionPerformed
        // TODO add your handling code here:
        img=fm.edgeSobel(img);
    }//GEN-LAST:event_btSobActionPerformed

    private void btSobXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSobXActionPerformed
        // TODO add your handling code here:
        img=fm.edgeSobelX(img);
    }//GEN-LAST:event_btSobXActionPerformed

    private void btSobYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSobYActionPerformed
        // TODO add your handling code here:
        img=fm.edgeSobelY(img);
    }//GEN-LAST:event_btSobYActionPerformed

    private void btPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPreActionPerformed
        // TODO add your handling code here:
        img=fm.edgePrewitt(img);
    }//GEN-LAST:event_btPreActionPerformed

    private void btPreNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPreNActionPerformed
        // TODO add your handling code here:
        img=fm.edgePrewitt2N(img);
    }//GEN-LAST:event_btPreNActionPerformed

    private void btPreNEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPreNEActionPerformed
        // TODO add your handling code here:
        img=fm.edgePrewitt2NE(img);
    }//GEN-LAST:event_btPreNEActionPerformed

    private void btPreEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPreEActionPerformed
        // TODO add your handling code here:
        img=fm.edgePrewitt2E(img);
    }//GEN-LAST:event_btPreEActionPerformed

    private void btPreSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPreSEActionPerformed
        // TODO add your handling code here:
        img=fm.edgePrewitt2SE(img);
    }//GEN-LAST:event_btPreSEActionPerformed

    private void btPreSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPreSActionPerformed
        // TODO add your handling code here:
        img=fm.edgePrewitt2S(img);
    }//GEN-LAST:event_btPreSActionPerformed

    private void btPreSWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPreSWActionPerformed
        // TODO add your handling code here:
        img=fm.edgePrewitt2SW(img);
    }//GEN-LAST:event_btPreSWActionPerformed

    private void btPreWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPreWActionPerformed
        // TODO add your handling code here:
        img=fm.edgePrewitt2W(img);
    }//GEN-LAST:event_btPreWActionPerformed

    private void btPreNWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPreNWActionPerformed
        // TODO add your handling code here:
        img=fm.edgePrewitt2NW(img);
    }//GEN-LAST:event_btPreNWActionPerformed

    private void btGrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGrayActionPerformed
        // TODO add your handling code here:
        img=hist.toGrayScale(img);
    }//GEN-LAST:event_btGrayActionPerformed

    private void btHistEQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHistEQActionPerformed
        // TODO add your handling code here:
        int[][] arrRGB=new int[3][img.getWidth()*img.getHeight()];
        int[][] sumRGB=new int[3][256];
        float[][] cdfRGB=new float[3][256];
        
        arrRGB=hist.getRGB(img);
        sumRGB=hist.sumRGB(img, arrRGB);
        hist.printHistogramRGB(sumRGB);
        cdfRGB=hist.cdfRGB(img, sumRGB);
        img=hist.histEq(img, cdfRGB);
    }//GEN-LAST:event_btHistEQActionPerformed

    private void btBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBack3ActionPerformed
        // TODO add your handling code here:
        this.setSize(defWIdth, defHeight);
        Pn_Hist.setVisible(false);
        Pn_Main.setVisible(true);
    }//GEN-LAST:event_btBack3ActionPerformed

    private void btHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHisActionPerformed
        // TODO add your handling code here:
        this.setSize(210, 230);
        Pn_Hist.setVisible(true);
        Pn_Main.setVisible(false);
    }//GEN-LAST:event_btHisActionPerformed

    private void btThreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThreshActionPerformed
        // TODO add your handling code here:
        img=sg.threshold(img);
    }//GEN-LAST:event_btThreshActionPerformed

    private void btBack4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBack4ActionPerformed
        // TODO add your handling code here:
        this.setSize(defWIdth, defHeight);
        Pn_Segment.setVisible(false);
        Pn_Main.setVisible(true);
    }//GEN-LAST:event_btBack4ActionPerformed

    private void btSegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSegActionPerformed
        // TODO add your handling code here:
        this.setSize(210, 230);
        Pn_Segment.setVisible(true);
        Pn_Main.setVisible(false);
    }//GEN-LAST:event_btSegActionPerformed

    private void btEroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEroActionPerformed
        // TODO add your handling code here:
        img=mp.erosion(img);
    }//GEN-LAST:event_btEroActionPerformed

    private void btBack5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBack5ActionPerformed
        // TODO add your handling code here:
        this.setSize(defWIdth, defHeight);
        Pn_Morph.setVisible(false);
        Pn_Main.setVisible(true);
    }//GEN-LAST:event_btBack5ActionPerformed

    private void btDilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDilActionPerformed
        // TODO add your handling code here:
        img=mp.dilation(img);
    }//GEN-LAST:event_btDilActionPerformed

    private void btMorpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMorpActionPerformed
        // TODO add your handling code here:
        this.setSize(210, 230);
        Pn_Morph.setVisible(true);
        Pn_Main.setVisible(false);
    }//GEN-LAST:event_btMorpActionPerformed

    private void btBinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBinActionPerformed
        // TODO add your handling code here:
        img=sg.binary(img);
    }//GEN-LAST:event_btBinActionPerformed

    private void btQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuantActionPerformed
        // TODO add your handling code here:
        img=qi.quantizeImage(img);
    }//GEN-LAST:event_btQuantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
        try {

            UIManager.setLookAndFeel( "com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
            }
            catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(PCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(PCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(PCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(PCD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pn_Filter;
    private javax.swing.JPanel Pn_Flip;
    private javax.swing.JPanel Pn_Hist;
    private javax.swing.JPanel Pn_Main;
    private javax.swing.JPanel Pn_Morph;
    private javax.swing.JPanel Pn_Segment;
    private javax.swing.JPanel Pn_Zoom;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel bg3;
    private javax.swing.JLabel bg4;
    private javax.swing.JLabel bgMain;
    private javax.swing.JButton btBack;
    private javax.swing.JButton btBack1;
    private javax.swing.JButton btBack2;
    private javax.swing.JButton btBack3;
    private javax.swing.JButton btBack4;
    private javax.swing.JButton btBack5;
    private javax.swing.JButton btBin;
    private javax.swing.JButton btCutPaste;
    private javax.swing.JButton btDil;
    private javax.swing.JButton btEdgeFr;
    private javax.swing.JButton btEdgeLap;
    private javax.swing.JButton btEdgeLapN;
    private javax.swing.JButton btEdgeLapP;
    private javax.swing.JButton btEro;
    private javax.swing.JButton btFil;
    private javax.swing.JButton btFlip;
    private javax.swing.JButton btGray;
    private javax.swing.JButton btHFlip;
    private javax.swing.JButton btHis;
    private javax.swing.JButton btHistEQ;
    private javax.swing.JButton btLoad;
    private javax.swing.JButton btMean;
    private javax.swing.JButton btMed;
    private javax.swing.JButton btMod;
    private javax.swing.JButton btMorp;
    private javax.swing.JButton btPre;
    private javax.swing.JButton btPreE;
    private javax.swing.JButton btPreN;
    private javax.swing.JButton btPreNE;
    private javax.swing.JButton btPreNW;
    private javax.swing.JButton btPreS;
    private javax.swing.JButton btPreSE;
    private javax.swing.JButton btPreSW;
    private javax.swing.JButton btPreW;
    private javax.swing.JButton btQuant;
    private javax.swing.JButton btResult;
    private javax.swing.JButton btSampling;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btSeg;
    private javax.swing.JButton btSharp;
    private javax.swing.JButton btSob;
    private javax.swing.JButton btSobX;
    private javax.swing.JButton btSobY;
    private javax.swing.JButton btThresh;
    private javax.swing.JButton btVFlip;
    private javax.swing.JButton btZIn;
    private javax.swing.JButton btZOut;
    private javax.swing.JButton btZoom;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton25;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfDir;
    private javax.swing.JTextField tfDirS;
    // End of variables declaration//GEN-END:variables
}
